### ISSUE TITLE
adb outdated

### ISSUE THREAD

**Issue by killshotSierra** [aakash-pamnani/ADB-QR#1]
![image](https://user-images.githubusercontent.com/97761336/166894296-6c788b74-94cd-4df6-a8ca-b6d1594b25a9.png)
when ı try to adb qr this happens any idea ?

**Comment by aakash-pamnani** [comment]
> ![image](https://user-images.githubusercontent.com/97761336/166894296-6c788b74-94cd-4df6-a8ca-b6d1594b25a9.png) when ı try to adb qr this happens any idea ?

open CMD and run adb --version and check which version you have of ADB
