### ISSUE TITLE
ADB-QR: error: protocol fault (couldn't read status message): Success

### ISSUE THREAD

**Issue by makis73** [aakash-pamnani/ADB-QR#11]
Trying with vscode in Linux and android 12 OnePlus phone. 
adb settings have been done and mobile data disabled.
Always show this error on vsCode after scanning QR code 
`ADB-QR: error: protocol fault (couldn't read status message): Success`

------------------
Found the reason of the error.
Maybe will be useful for someone.
I had connect my phone with vsCode via usb before. So the solution was not to "connect with QR code" but "connect with paired device"

**Comment by aakash-pamnani** [comment]
Hi can you share the logs when this error shows, need to check what causes this error msg.

open vscode > ctrl+shift+p > "Developer: Toggle Developer Tools"

Then try to connect with QR/Pairing code

After the error, Share the logs from the developer console window.

**Comment by makis73** [comment]
Sorry but pasting the text was not readable. I hope photo can help you.
Do you want to expand something of the below logs?

![Screenshot from 2023-12-10 14-32-39](https://github.com/aakash-pamnani/ADB-QR/assets/39548053/4bcf743a-df81-42a2-9303-98a72874b618)

**Comment by aakash-pamnani** [comment]
Thanks @makis73 for the screenshot will try to release a new version soon.

**Comment by makis73** [comment]
Thank you for your great work !!!! :)

**Comment by aakash-pamnani** [comment]
Hi @makis73, can you please update to latest version and check if the problem is solved or not?

**Comment by makis73** [comment]
Hi @aakash-pamnani,  v0.2.0 works! :)
![Screenshot from 2023-12-27 20-36-43](https://github.com/aakash-pamnani/ADB-QR/assets/39548053/6955ee6a-8ec6-4b15-90f8-de445dfc3e01)

Have a wonderful new year!

**Comment by aakash-pamnani** [comment]
Thank you! @makis73 
Wishing you a fantastic new year filled with joy and success.
