### ISSUE TITLE
Path

### ISSUE THREAD

**Issue by MHaddi1** [aakash-pamnani/ADB-QR#13]
ADB is not installed or PATH is not Configured

**Comment by aakash-pamnani** [comment]
@MHaddi1 check if adb is installed prop6in your system.

**Comment by mufaddalhamidofficial** [comment]
@aakash-pamnani It gives an error, Previously worked after I restarted vscode, but it does not work now even after restarting.

https://github.com/aakash-pamnani/ADB-QR/assets/49232863/ebbb2460-7d3e-4931-8223-14783277be5c

**Comment by aakash-pamnani** [comment]
@mufaddalhamidofficial can please open the console (vscode > help > open debugging tools) then perform same actions and share the logs.

**Comment by mufaddalhamidofficial** [comment]
Hey @aakash-pamnani, I tried to connect adb using Android Studio and it did not work either, so I restarted my PC and the extension then worked.
It is probably not an issue with your repo but I think it is an issue with your error message handling

**Comment by aakash-pamnani** [comment]
@mufaddalhamidofficial thanks for the reply.
But. I can't know what was the error to add the error message 🥹.

Closing the issue.
