### ISSUE TITLE
ADB is not updated please update to version 32 or later

### ISSUE THREAD

**Issue by nsaqib1** [aakash-pamnani/ADB-QR#3]
Whenever I try to connect with QR code that error shows

**Comment by aakash-pamnani** [comment]
@nsaqib1 check ADB version installed in your system.

**Comment by DevenValisten** [comment]
i have the same issue for a week, until i saw the installed adb is change, some software has its own adb file directory and changing the system adb target to its own.

**Comment by 689886sali** [comment]
http://go.microsoft.com/fwlink/?LinkId=827846

**Comment by 689886sali** [comment]
http://go.microsoft.com/fwlink/?LinkId=827846

**Comment by JVimes** [comment]
I get the error after installing the extension. I is gone after restarting VSCode.

**Comment by aakash-pamnani** [comment]
Run `adb --version` inside of vscode. If the version is less than 32 then update it to latest version.
