### ISSUE TITLE
ADB is not installed or PATH is not Configured

### ISSUE THREAD

**Issue by glennmichaelmejias** [aakash-pamnani/ADB-QR#4]

**Comment by aakash-pamnani** [comment]
You need to add ENV path of ADB in your system

**Comment by trwy7** [comment]
How do I do that?

**Comment by aakash-pamnani** [comment]
> 

https://developer.android.com/tools/releases/platform-tools

Download adb from here
And then install it 
https://www.xda-developers.com/install-adb-windows-macos-linux/

https://www.xda-developers.com/adb-fastboot-any-directory-windows-linux/?newsletter_popup=1


> How do I do that?
